# Generated by Django 2.0 on 2019-11-17 08:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default=None, max_length=1, null=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('signedup_on', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('anonymous', models.BooleanField(default=False)),
                ('avatar', models.CharField(blank=True, max_length=250, null=True)),
                ('firebase_signin_provider', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
