class InvalidResource(object):
    PAGE = 'INVALID_PAGE'
    PARAM = 'INVALID_PARAM'
    REQUEST_METHOD = 'INVALID_REQUEST_METHOD'
    SEARCH_QUERY = 'SEARCH_QUERY'

    DEVICE_INFO = 'INVALID_DEVICE_INFO'
    FCM_TOKEN = 'INVALID_FCM_TOKEN'

    USER_ID = 'INVALID_USER_ID'
    NAME = 'INVALID_NAME'
    PRICE = 'PRICE'
    RETAILER = 'retailer'
    PRODUCT = 'product'

    JWT_TOKEN = 'INVALID_JWT_TOKEN'


INVALID_RESOURCE = InvalidResource()
